import type { Config } from "tailwindcss";

const config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontSize: {
        base: "var(--fs-base)",
        displayLarge: "var(--fs-display-large)",
        displayMedium: "var(--fs-display-medium)",
        displaySmall: "var(--fs-display-small)",
        headlineLarge: "var(--fs-headline-large)",
        headlineMedium: "var(--fs-headline-medium)",
        headlineSmall: "var(--fs-headline-small)",
        titleLarge: "var(--fs-title-large)",
        titleMedium: "var(--fs-title-medium)",
        titleSmall: "var(--fs-title-small)",
        bodyLarge: "var(--fs-body-large)",
        bodyMedium: "var(--fs-body-medium)",
        bodySmall: "var(--fs-body-small)",
        labelLarge: "var(--fs-label-large)",
        labelMedium: "var(--fs-label-medium)",
        labelSmall: "var(--fs-label-small)",
      },
      lineHeight: {
        base: "var(--lh-base)",
        displayLarge: "var(--lh-display-large)",
        displayMedium: "var(--lh-display-medium)",
        displaySmall: "var(--lh-display-small)",
        headlineLarge: "var(--lh-headline-large)",
        headlineMedium: "var(--lh-headline-medium)",
        headlineSmall: "var(--lh-headline-small)",
        titleLarge: "var(--lh-title-large)",
        titleMedium: "var(--lh-title-medium)",
        titleSmall: "var(--lh-title-small)",
        bodyLarge: "var(--lh-body-large)",
        bodyMedium: "var(--lh-body-medium)",
        bodySmall: "var(--lh-body-small)",
        labelLarge: "var(--lh-label-large)",
        labelMedium: "var(--lh-label-medium)",
        labelSmall: "var(--lh-label-small)",
      },
      fontWeight: {
        regular: "var(--fw-regular)",
        medium: "var(--fw-medium)",
      },
      letterSpacing: {
        n025: "var(--ls-n-025)",
        p010: "var(--ls-p-010)",
        p015: "var(--ls-p-015)",
        p025: "var(--ls-p-025)",
        p040: "var(--ls-p-040)",
        p050: "var(--ls-p-050)",
      },
      spacing: {
        base: "var(--spacing-base)",
        half: "var(--spacing-05)",
        1: "var(--spacing-1)",
        2: "var(--spacing-2)",
        3: "var(--spacing-3)",
        4: "var(--spacing-4)",
        5: "var(--spacing-5)",
        6: "var(--spacing-6)",
        7: "var(--spacing-7)",
        8: "var(--spacing-8)",
        9: "var(--spacing-9)",
        10: "var(--spacing-10)",
        11: "var(--spacing-11)",
        12: "var(--spacing-12)",
        13: "var(--spacing-13)",
        14: "var(--spacing-14)",
        15: "var(--spacing-15)",
        16: "var(--spacing-16)",
        17: "var(--spacing-17)",
        18: "var(--spacing-18)",
        19: "var(--spacing-19)",
        20: "var(--spacing-20)",
      },
      boxShadow: {
        1: "var(--shadow-1)",
        2: "var(--shadow-2)",
        3: "var(--shadow-3)",
        4: "var(--shadow-4)",
        5: "var(--shadow-5)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;

export default config;
